Repository MohamedNiaissa/CareerProjectSymfony, pull requests merged in 2022-11, with the labels that each got.

#1 Project init
  .env
  .env.test
  .gitignore
  bin/console
  bin/phpunit
  composer.json
  composer.lock
  config/bundles.php
  config/packages/cache.yaml
  config/packages/debug.yaml
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/framework.yaml
  config/packages/mailer.yaml
  config/packages/messenger.yaml
  config/packages/monolog.yaml
  config/packages/notifier.yaml
  config/packages/routing.yaml
  config/packages/security.yaml
  config/packages/sensio_framework_extra.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/validator.yaml
  config/packages/web_profiler.yaml
  config/preload.php
  config/routes.yaml
  config/routes/framework.yaml
  config/routes/web_profiler.yaml
  config/services.yaml
  docker-compose.override.yml
  docker-compose.yml
  migrations/.gitignore
  phpunit.xml.dist
  public/index.php
  src/Controller/.gitignore
  src/Entity/.gitignore
  src/Kernel.php
  src/Repository/.gitignore
  symfony.lock
  templates/base.html.twig
  tests/bootstrap.php
  translations/.gitignore
Labels: GOTO STAGGING, development

#3 Feature/create company
  migrations/Version20221108162456.php
  src/Controller/CompanyController.php
  src/Entity/Company.php
  src/Form/Type/CompanyType.php
  src/Repository/CompanyRepository.php
  templates/Company/company.html.twig
Labels: development

#4 Implement basics documentation for the project.
  .gitignore
  AUTHORS.md
  HISTORY.md
  README.md
  migrations/Version20221108162456.php
  src/Controller/CompanyController.php
  src/Controller/README.md
  src/Entity/Company.php
  src/Form/Type/CompanyType.php
  src/Repository/CompanyRepository.php
  templates/Company/company.html.twig
  tests/README.md
Labels: documentation, GOTO STAGGING

#6 Rebasing on main-dev, pr went straight to main.
  .gitignore
  AUTHORS.md
  HISTORY.md
  README.md
  migrations/Version20221108162456.php
  src/Controller/README.md
  tests/README.md
Labels: GOTO STAGGING, IMPORTANT

#10 Feature/add bootstrap
  HISTORY.md
  composer.json
  config/bundles.php
  src/Components/FooterComponent.php
  src/Components/NavbarComponent.php
  symfony.lock
  templates/base.html.twig
  templates/components/footer.html.twig
  templates/components/navbar.html.twig
Labels: GOTO STAGGING, development, complete

#11 [v0.0.4] Fix/create company
  HISTORY.md
  migrations/Version20221108162456.php
  src/Controller/CompanyController.php
  src/Entity/Company.php
Labels: fixed, development, complete

#8 [v0.0.5] Implement custom commands app:jobs <param>
  HISTORY.md
  completion.sh
  src/Command/CreateJobsCommand.php
  src/Command/README.md
Labels: GOTO STAGGING, feature, development

#7 [v0.0.6] Implement Mailer Service
  HISTORY.md
  composer.lock
  src/Service/Mailer.php
  src/Service/README.md
Labels: GOTO STAGGING, feature, development

#9 [v0.0.7-beta] Implement Skill Entity, Fixture
  HISTORY.md
  composer.json
  composer.lock
  config/bundles.php
  docker-compose.yml
  migrations/README.md
  migrations/Version20221109085905.php
  src/DataFixtures/README.md
  src/DataFixtures/SkillFixtures.php
  src/Entity/Skill.php
  src/Repository/SkillRepository.php
  symfony.lock
Labels: GOTO STAGGING, feature, development

#13 [v.0.0.7] Config/docker
  HISTORY.md
  docker-compose.yml
Labels: GOTO STAGGING, IMPORTANT, fixed

#15 [v0.0.8] Feature/candidate form
  HISTORY.md
  migrations/Version20221109140935.php
  src/Controller/CandidateController.php
  src/DataFixtures/CandidateFixtures.php
  src/Entity/Candidate.php
  src/Form/Type/CandidateType.php
  src/Repository/CandidateRepository.php
  templates/candidate/candidate.html.twig
Labels: GOTO STAGGING, feature, development

#12 [v0.0.9] Added first unit test class
  HISTORY.md
  src/Service/CalcService.php
  tests/Service/CalcServiceTest.php
Labels: GOTO STAGGING, feature, development

#16 [v0.0.10] Implement Job Entity, Controller, Template with form
  HISTORY.md
  README.md
  migrations/README.md
  migrations/Version20221109134322.php
  src/Controller/CompanyController.php
  src/Controller/JobController.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Form/Type/JobType.php
  src/Repository/JobRepository.php
  templates/job/index.html.twig
  templates/job/job.html.twig
Labels: GOTO STAGGING, feature, development

#17 [v0.0.11] Feature/get companies
  HISTORY.md
  composer.lock
  src/Controller/CompanyController.php
  templates/Company/company.html.twig
Labels: GOTO STAGGING, feature, development, complete

#22 Removed all problematic version
  migrations/README.md
  migrations/deprecated/README.md
  migrations/deprecated/Version20221108162456.php
  migrations/deprecated/Version20221109085905.php
  migrations/deprecated/Version20221109134322.php
  migrations/deprecated/Version20221109140935.php
  migrations/deprecated/Version20221109160233.php
Labels: critical

#23 Implement User entity and repository with relation
  migrations/README.md
  migrations/Version20221109200222.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Repository/CandidateRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/SkillRepository.php
  src/Repository/UserRepository.php
Labels: development, complete

#20 [v.0.0.12], fix the migrations again
  HISTORY.md
  migrations/Version20221109140935.php
Labels: GOTO STAGGING, IMPORTANT, critical, fixed

#24 Implemented Security Controller and Registration Controller
  config/packages/security.yaml
  src/Controller/JobController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  src/Security/LoginAuthAuthenticator.php
  templates/base.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
  translations/security.en.yaml
Labels: feature, complete

#25 Added auth checkup for the navigation bar
  templates/base.html.twig
  templates/components/navbar.html.twig
Labels: feature, complete

#28 Fix template design, and resolve Collection error
  src/Controller/CandidateController.php
  src/Entity/Company.php
  src/Form/Type/CompanyType.php
  templates/Company/company.html.twig
  templates/candidate/candidate.html.twig
  templates/components/footer.html.twig
Labels: feature, complete

#21 [v0.1.0] Integrate authentification with roles
  config/packages/security.yaml
  migrations/README.md
  migrations/Version20221109200222.php
  migrations/deprecated/README.md
  migrations/deprecated/Version20221108162456.php
  migrations/deprecated/Version20221109085905.php
  migrations/deprecated/Version20221109134322.php
  migrations/deprecated/Version20221109140935.php
  migrations/deprecated/Version20221109160233.php
  src/Controller/CandidateController.php
  src/Controller/CompanyController.php
  src/Controller/JobController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/CandidateRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/SkillRepository.php
  src/Repository/UserRepository.php
  src/Security/LoginAuthAuthenticator.php
  templates/base.html.twig
  templates/components/footer.html.twig
  templates/components/navbar.html.twig
  templates/home/home.html.twig
  templates/job/index.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
  translations/security.en.yaml
Labels: GOTO STAGGING, development

#27 [v0.1.1] Templating
  src/Controller/CandidateController.php
  src/Entity/Company.php
  src/Form/Type/CompanyType.php
  templates/Company/company.html.twig
  templates/candidate/candidate.html.twig
  templates/components/footer.html.twig
Labels: GOTO STAGGING, feature, development

#30 Fix/role profile creation
  migrations/README.md
  migrations/Version20221110085916.php
  src/Controller/CandidateController.php
  src/Controller/CompanyController.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/User.php
Labels: GOTO STAGGING, fixed, complete

#31 Feature/create job offer
  migrations/Version20221110102900.php
  src/Controller/JobController.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Form/Type/JobType.php
Labels: feature, development, complete

#32 Feature/template and querybuilder
  src/Controller/JobController.php
  src/DataFixtures/CandidateFixtures.php
  src/Entity/Skill.php
  src/Form/Type/CandidateType.php
  src/Form/Type/CompanyType.php
  templates/candidate/candidate.html.twig
  templates/job/index.html.twig
Labels: development

#33 Feature/implement job service in command
  migrations/Version20221110112042.php
  src/Command/CreateJobsCommand.php
  src/Controller/JobController.php
  src/Entity/Job.php
  src/Service/JobManager.php
Labels: GOTO STAGGING, feature, development, complete

#37 Fix/main conflict
  HISTORY.md
  migrations/README.md
Labels: GOTO STAGGING, fixed, complete

#35 [v0.1.2-beta] Main dev
  HISTORY.md
  README.md
  composer.lock
  config/packages/security.yaml
  migrations/README.md
  migrations/Version20221109200222.php
  migrations/Version20221110085916.php
  migrations/Version20221110102900.php
  migrations/Version20221110112042.php
  migrations/deprecated/README.md
  migrations/deprecated/Version20221108162456.php
  migrations/deprecated/Version20221109085905.php
  migrations/deprecated/Version20221109134322.php
  migrations/deprecated/Version20221109140935.php
  migrations/deprecated/Version20221109160233.php
  src/Command/CreateJobsCommand.php
  src/Controller/CandidateController.php
  src/Controller/CompanyController.php
  src/Controller/JobController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Form/Type/CandidateType.php
  src/Form/Type/CompanyType.php
  src/Form/Type/JobType.php
  src/Repository/CandidateRepository.php
  src/Repository/JobRepository.php
  src/Repository/UserRepository.php
  src/Security/LoginAuthAuthenticator.php
  src/Service/CalcService.php
  src/Service/JobManager.php
  templates/base.html.twig
  templates/candidate/candidate.html.twig
  templates/company/pending.html.twig
  templates/company/profile.html.twig
  templates/components/footer.html.twig
  templates/components/navbar.html.twig
  templates/home/home.html.twig
  templates/job/index.html.twig
  templates/job/job.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
  tests/Service/CalcServiceTest.php
  translations/security.en.yaml
Labels: GOTO PROD
